# Generated by Django 4.2.11 on 2024-03-07 14:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_student_photo_alter_event_attending'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
