# Generated by Django 4.2.11 on 2024-03-07 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_attending'),
        ('event', '0005_event_photo'),
    ]

    operations = [
    ]
