# Generated by Django 4.2.11 on 2024-03-08 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_photo_alter_event_photo_alter_student_photo'),
        ('event', '0007_review'),
    ]

    operations = [
    ]
