# Generated by Django 4.2.11 on 2024-03-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_event_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
